language: java
jdk:
  - oraclejdk8
notifications:
  email:
    recipients:
      - francois.fouquet@uni.lu
      - gregory.nain@uni.lu
      - thomas.hartmann@uni.lu
      - assaad.moawad@uni.lu
      - ludovic.mouline@uni.lu
      - andrey.boytsov@uni.lu
    on_success: change
    on_failure: change

#Compile only master branch
branches:
  only:
    - master

before_install:
  - sudo apt-get purge nodejs npm
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get -qq update
  - sudo apt-get install nodejs
  - node -version